[package]
name = "tudelft-thesis"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Victor Vreede"]
license = "CC-BY-NC"
description = "A template for a thesis report in TU Delft style."
compiler = "0.13.1"

[template]
path = "template"
entrypoint = "doc.typ"
thumbnail = "thumbnail.png"

